services:
  mail-service:
    build: .
    container_name: mail-service
    restart: always
    command: [ "uv", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000" ]
    environment:
      - ENVIRONMENT=DEV
    ports:
      - "8001:8000"
    volumes:
      - ./logs:/mail-service/logs
    networks:
      - pomodoro-net


networks:
  pomodoro-net:
    external: true